config/urls.py
# ruff: noqa
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include
from django.urls import path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    # path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("dj.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("leagues/", include("dj.leagues.urls", namespace="leagues")),
    path("matches/", include("dj.matches.urls", namespace="matches")),
    path("players/", include("dj.players.urls", namespace="players")),
    path("teams/", include("dj.teams.urls", namespace="teams")),
    path("heroes/", include("dj.heroes.urls", namespace="heroes")),
    # Media files
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

dj/common/urls.py
API = 'https://api.stratz.com/api/v1'
URL_LAST_100_LEAGUES = f'{API}/league?take=100&orderBy=-startDateTime'
OPENDOTA_API = 'https://api.opendota.com/api'


def get_url_league_list(take: int = 250, order_by: str = '-id') -> str:
    return f'{API}/league?take={take}&orderBy={order_by}'


def get_url_league_match_list(league_id: int, take: int = 500, skip: int = 0) -> str:
    return f'{API}/league/{league_id}/matches?take={take}&skip={skip}'


def get_url_league_series_list(league_id: int, take: int = 500, skip: int = 0) -> str:
    return f'{API}/league/{league_id}/series?take={take}&skip={skip}'


def get_url_team(team_id: int = 0) -> str:
    return f'{API}/team/{team_id}'


def get_url_match(match_id: int = 0) -> str:
    return f'{API}/match/{match_id}'


def get_url_pro_steam_acc() -> str:
    return f'{API}/player/proSteamAccount'


def get_url_player(player_id: int = 0) -> str:
    return f'{API}/player/{player_id}'


def get_url_heroes() -> str:
    return f'{API}/Hero'


def get_opendota_teams() -> str:
    return f'{OPENDOTA_API}/explorer?sql=SELECT%20teams.*%2C%20team_rating.*%2C%0ASTRING_AGG(distinct(team_match.match_id%3A%3Acharacter%20varying)%2C%20%27%2C%20%27)%20as%20matches_ids%0AFROM%20teams%20%0ALEFT%20JOIN%20team_rating%20ON%20team_rating.team_id%20%3D%20teams.team_id%20%0ALEFT%20JOIN%20team_match%20ON%20team_match.team_id%20%3D%20teams.team_id%0ALEFT%20JOIN%20match_patch%20ON%20match_patch.match_id%20%3D%20team_match.match_id%0AWHERE%20team_rating.rating%20%3E%3D%201100%20AND%20match_patch.patch%20%3E%3D%20%277.33%27%0AGROUP%20BY%20teams.team_id%2C%20team_rating.team_id%0AORDER%20BY%20team_rating.rating%20DESC%0A%0A'

dj/teams/urls.py
# Create your views here.
from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views

app_name = "teams"

urlpatterns = [
    path("<int:id>/", views.team_detail_view, name="team_detail"),
    path("update/<int:team_id>/", login_required(views.update_team_data), name="update_item"),
    path("", views.team_list_view, name="team_list"),
    path("update/", views.get_teams, name="teams_update"),
]

dj/users/urls.py
from django.urls import path

from .views import user_detail_view
from .views import user_redirect_view
from .views import user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

dj/players/forms.py
from django import forms

from .models import SteamAccount, ProSteamAccount


class SteamAccountForm(forms.ModelForm):
    class Meta:
        model = SteamAccount
        fields = '__all__'


class ProSteamAccountForm(forms.ModelForm):
    class Meta:
        model = ProSteamAccount
        fields = '__all__'

dj/heroes/views.py
from django.views.generic import ListView

from dj.heroes.models import Hero


# Create your views here.


class HeroesListView(ListView):
    model = Hero
    paginate_by = 25


heroes_list_view = HeroesListView.as_view()

dj/leagues/views.py
from celery import current_app
from django.contrib import messages
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import redirect
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.http import require_POST, require_GET
from django.views.generic import ListView, DetailView
from orjson import orjson

from dj.leagues.models import League, Series


class LeagueListView(ListView):
    model = League
    paginate_by = 25

    def get_queryset(self):
        return League.objects.tier2()


league_list_view = LeagueListView.as_view()


class LeagueDetailView(DetailView):
    model = League
    slug_field = "id"
    slug_url_kwarg = "league_id"
    paginate_by = 25

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        league = self.object

        # Get series and paginate
        series = league.series.active().select_related(
            'team_one', 'team_two'
        )

        page_obj = self.paginate_series(series)
        teams = self.get_teams(series)
        # graph_data = get_hero_data(league.id, 'league')

        context.update({
            'teams': teams,
            'page_obj': page_obj,
        })
        return context

    def paginate_series(self, series):
        paginator = Paginator(series, self.paginate_by)
        page_number = self.request.GET.get('page')
        return paginator.get_page(page_number)

    @staticmethod
    def get_teams(series):
        team_ids = set()
        for series_obj in series:
            team_ids.add(series_obj.team_one)
            team_ids.add(series_obj.team_two)
        return list(team_ids)


# Usage
league_detail_view = LeagueDetailView.as_view()


@csrf_protect
@require_POST
def update_leagues_list(request):
    try:
        current_app.send_task(name="dj.leagues.tasks.task_get_and_save_leagues_list")
        messages.success(request, 'Task "Update Leagues" is running!')
    except Exception as e:
        messages.error(
            request,
            f'Exception occurred while running the task "Update Leagues": {str(e)}',
        )

    return redirect("/leagues/")


@csrf_protect
@require_POST
def update_league_data(request, league_id):
    if not league_id:
        messages.error(request, "League ID is required.")
        return redirect(request.META.get("HTTP_REFERER", "/"))
    try:
        league, _ = League.objects.get_or_create(id=league_id)
        current_app.send_task(
            "dj.leagues.tasks.task_get_and_save_league_series", args=[league.id, True]
        )
        messages.success(request, 'Task "Update League Data" is running!')
    except League.DoesNotExist:
        messages.error(request, "League not found.")
    except Exception as e:
        messages.error(request, f"Exception occurred: {str(e)}")

    return redirect(f"/leagues/{league_id}/")


@csrf_protect
@require_GET
def update_series_matches(request, series_id):
    try:
        series, _ = Series.objects.get_or_create(id=series_id)
        series_data = {
            'id': series.id,
            'win': series.winning_team_id,
        }
        current_app.send_task(
            "dj.matches.tasks.task_get_and_save_object_matches", args=['series', series_id]
        )
        response_data = orjson.dumps(series_data)
        return HttpResponse(response_data, content_type='application/json')
    except Series.DoesNotExist:
        response_data = orjson.dumps({'error': 'Series not found'})
        return HttpResponse(response_data, content_type='application/json', status=404)

dj/matches/views.py
from django.db.models import Q
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.http import require_GET
from django.views.generic import ListView, DetailView

from dj.common.constants import PLAYER
from dj.matches.models import Match
from dj.matches.services import get_hero_data, get_hero_data_for_player


class MatchListView(ListView):
    model = Match
    paginate_by = 25

    def get_queryset(self):
        return Match.active_objects()


match_list_view = MatchListView.as_view()


class MatchDetailView(DetailView):
    model = Match
    slug_field = "id"
    slug_url_kwarg = "id"


match_detail_view = MatchDetailView.as_view()


@csrf_protect
@require_GET
def get_heroes_in_matches(request):
    try:
        type_obj = request.GET.get('type_obj')
        id_obj = request.GET.get('id_obj')
        league_id = request.GET.get('league_id')
        team_id = request.GET.get('team_id')
        start_date_time = request.GET.get('start_date_time')
        duration_seconds = request.GET.get('duration_seconds')

        if not type_obj or not id_obj:
            return JsonResponse({'error': 'Missing type_obj or id_obj parameter'}, status=400)

        filters = Q(game_version_id=175)
        if league_id:
            filters &= Q(league__id=league_id)
        if team_id:
            filters &= (Q(radiant_team__id=team_id) | Q(dire_team__id=team_id))
        if start_date_time:
            filters &= Q(start_date_time__gte=start_date_time)
        if duration_seconds:
            filters &= Q(duration_seconds__gte=duration_seconds)
        if type_obj == PLAYER:
            data = get_hero_data_for_player(id_obj, filters)
        else:
            data = get_hero_data(id_obj, type_obj, filters)
        return JsonResponse(data, safe=False)
    except Exception as e:
        return JsonResponse({'error': str(e)}, status=500)

dj/players/views.py
from celery import current_app
from django.contrib import messages
from django.shortcuts import redirect
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.http import require_POST
from django.views.generic import ListView, DetailView

from dj.players.models import Player
from dj.players.models import SteamAccount


class PlayerListView(ListView):
    model = Player
    paginate_by = 25

    def get_queryset(self):
        return Player.objects.pro_player()


player_list_view = PlayerListView.as_view()


class PlayerDetailView(DetailView):
    model = Player
    slug_field = "id"
    slug_url_kwarg = "player_id"


player_detail_view = PlayerDetailView.as_view()


@csrf_protect
@require_POST
def get_players(request):
    try:
        current_app.send_task(name="dj.players.tasks.task_get_and_save_pro_players_list")
        messages.success(request, 'Task "Update Players" is running!')
    except Exception as e:
        messages.error(
            request,
            f'Exception occurred while running the task "Update Players": {str(e)}',
        )
    return redirect("/players/")


@csrf_protect
@require_POST
def update_player_data(request, player_id):
    if not player_id:
        messages.error(request, "Account ID is required.")
        return redirect(request.META.get("HTTP_REFERER", "/"))

    try:
        current_app.send_task(
            "dj.players.tasks.get_and_save_player_data", args=[player_id]
        )
        messages.success(request, 'Task "Update Player Data" is running!')
    except SteamAccount.DoesNotExist:
        messages.error(request, "Player not found.")
    except Exception as e:
        messages.error(request, f"Exception occurred: {str(e)}")

    return redirect(f"/players/{player_id}/")

dj/stats/views.py
from django.shortcuts import render

# Create your views here.

dj/teams/views.py
from celery import current_app
from django.contrib import messages
from django.db.models import Q
from django.shortcuts import redirect
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.http import require_POST
from django.views.generic import DetailView
from django.views.generic import ListView

from dj.leagues.models import League
from dj.matches.models import Match
from dj.teams.models import Team


class TeamListView(ListView):
    model = Team
    paginate_by = 25

    def get_queryset(self):
        # Calculate win_ratio with proper handling of null and zero values
        return Team.objects.is_pro()
    #
    # .annotate(
    #     win_ratio=ExpressionWrapper(
    #         Case(
    #             When(win_count__isnull=True, then=Value(0)),
    #             When(loss_count__isnull=True, then=Value(0)),
    #             When(win_count=0, then=Value(0)),
    #             When(loss_count=0, then=Value(0)),
    #             default=F('win_count') * 100.0 / (F('win_count') + F('loss_count')),
    #             output_field=FloatField()
    #         ),
    #         output_field=FloatField()
    #     )
    # ).order_by('-win_ratio')


team_list_view = TeamListView.as_view()


class TeamDetailView(DetailView):
    """
    View for displaying detailed information about a team.
    """
    model = Team
    slug_field = "id"
    slug_url_kwarg = "id"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        team = self.object

        # matches = self.get_team_matches(team)
        leagues = self.get_team_leagues(team)

        context.update({
            # 'matches': matches,
            'leagues': leagues,
        })
        return context

    @staticmethod
    def get_team_matches(team):
        """
        Retrieve matches where the team participates.
        """
        return Match.active_objects().filter(
            Q(radiant_team_id=team.id) | Q(dire_team_id=team.id)
        )

    @staticmethod
    def get_team_leagues(team):
        """
        Retrieve leagues where the team participates.
        """
        return League.active_objects().filter(
            Q(series__team_one_id=team.id) | Q(series__team_two_id=team.id)
        ).distinct()


# Create an instance of TeamDetailView for URL routing
team_detail_view = TeamDetailView.as_view()


@csrf_protect
@require_POST
def update_team_data(request, team_id):
    if not team_id:
        messages.error(request, "Team ID is required.")
        return redirect(request.META.get("HTTP_REFERER", "/"))

    try:
        Team.objects.get_or_create(id=team_id)
        current_app.send_task("dj.teams.tasks.get_and_save_team_data", args=[team_id])
        messages.success(request, 'Task "Update Team Data" is running!')
    except Team.DoesNotExist:
        messages.error(request, "Team not found.")
    except Exception as e:
        messages.error(request, f"Exception occurred: {str(e)}")

    return redirect(f"/teams/{team_id}/")


@csrf_protect
@require_POST
def get_teams(request):
    try:
        current_app.send_task(name="dj.teams.tasks.task_get_and_save_teams_list")
        messages.success(request, 'Task "Update Teams" is running!')
    except Exception as e:
        messages.error(
            request,
            f'Exception occurred while running the task "Update Teams": {str(e)}',
        )
    return redirect("/teams/")

dj/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView
from django.views.generic import RedirectView
from django.views.generic import UpdateView

from dj.users.models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        # for mypy to know that the user is authenticated
        assert self.request.user.is_authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

dj/templates/teams/team_detail.html
{% extends "base.html" %}

{% load static %}

{% block title %}
  Team: {{ team.name }}
{% endblock title %}

{% block content %}
  <div class="container mt-5">
    <div class="row">
      <div class="col-lg-12">
        <article>
          <header class="mb-4">
            <h1 class="fw-bolder mb-1">{{ team.name }} - {{ team.tag }}</h1>
            <div class="text-muted fst-italic mb-2">Last on: {{ team.last_match_date_time }}</div>
            <span class="badge bg-secondary text-decoration-none link-light">W: {{ team.win_count }}</span>
            <span class="badge bg-secondary text-decoration-none link-light">L: {{ team.loss_count }}</span>
          </header>
        </article>
      </div>
    </div>
    <div class="row pt-3">
      <div class="col-md-4">
        {% include 'teams/includes/team_info.html' %}
      </div>
      <div class="col-md-8">
        <div class="p-1" id="pr-heroes-bar-team"></div>
        <div class="card mb-1">
          <div class="card-body">
            {% include 'common/match/heroes_bar_chart.html' %}
          </div>
        </div>
        {% if heroes %}
          <div id="heroes" class="pt-1">
            <div class="card">
              <div class="card-header">
                <a class="btn btn-primary" data-bs-toggle="collapse" href="#collapseHeroes">
                  Popular Heroes
                </a>
              </div>
              <div id="collapseHeroes" class="collapse" data-bs-parent="#leagues">
                <div class="card-body">
                  {% include 'common/match/pie_chart_heroes.html' %}
                </div>
              </div>
            </div>
          </div>
          <div id="picks" class="pt-1">
            <div class="card">
              <div class="card-header">
                <a class="btn btn-primary" data-bs-toggle="collapse" href="#collapsePicks">
                  Picks
                </a>
              </div>
              <div id="collapsePicks" class="collapse" data-bs-parent="#leagues">
                <div class="card-body">
                  {% include 'common/match/graph_picks.html' %}
                </div>
              </div>
            </div>
          </div>
        {% endif %}
        <div id="members" class="pt-1">
          <div class="card">
            <div class="card-header">
              <a class="btn btn-primary" data-bs-toggle="collapse" href="#collapseMembers">
                Current Team Members
              </a>
            </div>
            <div id="collapseMembers" class="collapse" data-bs-parent="#leagues">
              <div class="card-body">
                {% include 'teams/includes/team_members.html' with members=team.get_members|slice:":5" %}
              </div>
            </div>
          </div>
        </div>
        <div id="members-old" class="pt-1">
          <div class="card">
            <div class="card-header">
              <a class="btn btn-primary" data-bs-toggle="collapse" href="#collapseMembersOld">
                Old Team Members
              </a>
            </div>
            <div id="collapseMembersOld" class="collapse" data-bs-parent="#leagues">
              <div class="card-body">
                {% include 'teams/includes/team_members.html' with members=team.get_members|slice:"5:" %}
              </div>
            </div>
          </div>
        </div>
        {% if leagues %}
          <div id="team-leagues" class="pt-1">
            <div class="card">
              <div class="card-header">
                <a class="btn btn-primary" data-bs-toggle="collapse" href="#collapseTeamLeagues">
                  Leagues racing
                </a>
              </div>
              <div id="collapseTeamLeagues" class="collapse" data-bs-parent="#leagues">
                <div class="card-body">
                  {% include 'teams/includes/team_leagues.html' %}
                </div>
              </div>
            </div>
          </div>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock content %}

{% block inline_javascript %}
  <script src="https://d3js.org/d3.v7.min.js"></script>
  <script>
    document.addEventListener("DOMContentLoaded", function () {
      fetchDataAndCreateCharts("type_obj=team&id_obj={{ team.id }}", 'pr-heroes-bar-team').then(data => {
        if (data) {
          createBarChart("#heroes-bar-chart", data.nodes_picks);
          createBarChart("#heroes-bar-chart-bans", data.nodes_bans);
          createPieChart('#pieChartPicks', data.nodes_picks);
          createPieChart('#pieChartBans', data.nodes_bans);
          createHeroGraph('#graph', data.nodes_picks, data.links_picks);
        } else {
          console.error('Error fetching heroes data:', data.error);
        }
      });
    })
  </script>
{% endblock inline_javascript %}

dj/templates/teams/team_list.html
{% extends "base.html" %}

{% load static %}

{% block title %}
  Teams: {{ team_list|length }}
{% endblock title %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-sm-12 p-2">
        <div class="col-sm-12 p-4 text-center">
          <h1><a href="{% url 'teams:team_list' %}">Teams</a></h1>
          {% if request.user.is_authenticated %}
            <form method="POST" action="{% url 'teams:teams_update' %}">
              {% csrf_token %}
              <button type="submit" class="btn btn-primary m-2">Update Teams</button>
            </form>
          {% endif %}
        </div>
        {% if team_list %}
          <table class="table table-hover">
            <thead>
            <tr>
              <th class="text-center" scope="col">Id</th>
              <th scope="col">Name</th>
              <th class="text-center" scope="col">win_count</th>
              <th class="text-center" scope="col">loss_count</th>
              <th class="text-center" scope="col">win_ratio</th>
              <th class="text-center" scope="col">tag</th>
              <th class="text-center" scope="col">Updated</th>
              <th class="text-center" scope="col">last_match</th>
            </tr>
            </thead>
            <tbody>
            {% for team in team_list %}
              <tr {% if team.win_ratio > 60 %} class="table-primary" {% endif %}>
                <th scope="row"><a href="{{ team.get_absolute_url }}">{{ team.id }}</a></th>
                <td>{{ team.name }}</td>
                <td>{{ team.win_count }}</td>
                <td>{{ team.loss_count }}</td>
                <td class="text-center {% if team.rank > 1400 %} table-success{% endif %}">{{ team.rank }}
                </td>
                <td>{{ team.tag }}</td>
                <td>{{ team.get_last_update }}</td>
                <td>{{ team.get_verbose_last_match_date_time }}</td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
        {% else %}
          <p>There are no teams in the library.</p>
        {% endif %}
      </div>
      {% include 'pagination.html' %}
    </div>
  </div>
{% endblock content %}